[profile.default]
src = 'contracts'
out = 'out'
test = 'test'
libs = ['node_modules', 'lib']
script = 'scripts/foundry'
cache_path = 'cache-forge'
gas_reports = ["*"]
via_ir = false
sizes = true
optimizer_runs=1000
solc_version = '0.8.19'
fs_permissions = [{ access = "read-write", path = "./scripts/foundry/transaction.json"}]

ffi = true

[rpc_endpoints]
arbitrum = "${ETH_NODE_URI_ARBITRUM}"
gnosis = "${ETH_NODE_URI_GNOSIS}"
mainnet = "${ETH_NODE_URI_MAINNET}"
optimism = "${ETH_NODE_URI_OPTIMISM}"
polygon = "${ETH_NODE_URI_POLYGON}"
fork = "${ETH_NODE_URI_FORK}"
avalanche = "${ETH_NODE_URI_AVALANCHE}"
celo = "${ETH_NODE_URI_CELO}"
polygonzkevm = "${ETH_NODE_URI_POLYGONZKEVM}"
bsc = "${ETH_NODE_URI_BSC}"
base = "${ETH_NODE_URI_BASE}"
linea = "${ETH_NODE_URI_LINEA}"
mantle = "${ETH_NODE_URI_MANTLE}"
